server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: sjkim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        jdbc:
#          time_zone: Asia/Seoul
    defer-datasource-initialization: true
  sql:
    init:
      mode: always