server:
  port: 9055

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2: # Login saved settings: Generic H2 (Server)
    console:
      enabled: true
      path: /h2-console  # http://localhost:9055/h2-console
  datasource:
    url: jdbc:h2:mem:userdetails-test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
