server:
  port: 9055

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true