version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-study
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./datadir:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d/