version: "3"
services:
  db:
    image: postgres
    container_name: postgres-study
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./datadir:/var/lib/postgresql/data
      - ./init.d.sql:/docker-entrypoint-initdb.d/init.d.sql